### ISSUE TITLE
Chef with cron

### ISSUE THREAD

**Issue by tobymaro** [Dynatrace/Dynatrace-Chef#24]
Hello,

Usually I run chef-client every 5 minutes on all my nodes. But new cookbook version doesn't allow it. It restarts server and collectors every run. 
Could you please correct it? For example add to your resources  "updated_by_last_action?"

**Comment by pozieblo** [comment]
The fix is ready on master branch (see commits dcab881e1, fd42006a2 and c99d80df4). Specifically the following scenarios have been analyzed and taken into account in this fix:
* First chef run (clean install) - The service is started only once after being fully configured
* Second chef run without changing the configuration - no changes should be observed
* Subsequent chef run after configuration has been changed (e.g. the ini file parameters for the Dynatrace Server) - only one service restart should be observed 
* Chef run after changing the installer link - an error should be reported. We do not support smooth migration from one version of a package to another.
As part of this ticket we also removed the configuration of the externalhostname attribute in the server.config.xml which caused restart of the Dynatrace Server on each Chef run.

**Comment by tobymaro** [comment]
Thank you. What about chef supermarket? I think it's better to set new version. I used Berks and it downloads old code version.

**Comment by pozieblo** [comment]
We will release an official version tomorrow (on Tuesday).

**Comment by tobymaro** [comment]
Thank You. It's Ok now.
